groups:
  - name: ai_admin_alerts
    interval: 30s
    rules:
      # Высокий процент ошибок
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(ai_admin_http_requests_total{status=~"5.."}[5m])) /
            sum(rate(ai_admin_http_requests_total[5m]))
          ) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes"

      # AI провайдер недоступен
      - alert: AIProviderDown
        expr: |
          (
            sum(rate(ai_admin_ai_provider_errors_total[5m])) /
            sum(rate(ai_admin_ai_provider_duration_seconds_count[5m]))
          ) > 0.5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "AI provider experiencing high error rate"
          description: "AI provider {{ $labels.provider }} has {{ $value | humanizePercentage }} error rate"

      # Circuit Breaker открыт
      - alert: CircuitBreakerOpen
        expr: ai_admin_circuit_breaker_state > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Circuit breaker is open"
          description: "Circuit breaker for {{ $labels.service }} has been open for 2 minutes"

      # Высокая латентность AI
      - alert: HighAILatency
        expr: |
          histogram_quantile(0.95,
            sum(rate(ai_admin_ai_provider_duration_seconds_bucket[5m])) by (le, provider)
          ) > 5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High AI provider latency"
          description: "95th percentile latency for {{ $labels.provider }} is {{ $value }}s"

      # Низкий Cache Hit Rate
      - alert: LowCacheHitRate
        expr: ai_admin_cache_hit_rate < 50
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate for {{ $labels.cache_type }} is {{ $value }}%"

      # Много заблокированных Rate Limiter
      - alert: HighRateLimiterBlocks
        expr: |
          (
            sum(rate(ai_admin_rate_limiter_blocked_total[5m])) /
            sum(rate(ai_admin_rate_limiter_allowed_total[5m]))
          ) > 0.2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High rate of blocked requests"
          description: "{{ $value | humanizePercentage }} of requests are being rate limited"

      # База данных медленная
      - alert: SlowDatabaseQueries
        expr: |
          histogram_quantile(0.95,
            sum(rate(ai_admin_database_query_duration_seconds_bucket[5m])) by (le, operation)
          ) > 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries detected"
          description: "95th percentile for {{ $labels.operation }} is {{ $value }}s"

      # Низкий процент успешных команд
      - alert: LowCommandSuccessRate
        expr: |
          (
            sum(rate(ai_admin_command_executions_total{status="success"}[5m])) by (command) /
            sum(rate(ai_admin_command_executions_total[5m])) by (command)
          ) < 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low command success rate"
          description: "Command {{ $labels.command }} has only {{ $value | humanizePercentage }} success rate"

      # Много активных разговоров
      - alert: HighActiveConversations
        expr: ai_admin_active_conversations > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of active conversations"
          description: "{{ $value }} active conversations (threshold: 1000)"

      # Долгая обработка сообщений
      - alert: SlowMessageProcessing
        expr: |
          histogram_quantile(0.95,
            sum(rate(ai_admin_message_processing_duration_seconds_bucket[5m])) by (le)
          ) > 10
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "Message processing is slow"
          description: "95th percentile message processing time is {{ $value }}s"

      # Память процесса
      - alert: HighMemoryUsage
        expr: |
          (
            ai_admin_process_resident_memory_bytes /
            ai_admin_process_heap_bytes
          ) > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Process is using {{ $value | humanizePercentage }} of available memory"

      # CPU использование
      - alert: HighCPUUsage
        expr: rate(ai_admin_process_cpu_seconds_total[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "Process CPU usage is {{ $value | humanizePercentage }}"